"""Bump the repo's VERSION file (``Major.Minor.Patch``).

VERSION is the single source of truth — ``pyproject.toml`` reads it via
``[tool.setuptools.dynamic]``. It is always a plain ``X.Y.Z`` on ``development`` and ``main``:

* every merge to ``development`` -> ``ver.project_bump_patch``  (``0.2.0`` -> ``0.2.1``)
* a release just **promotes + tags** whatever ``development`` is at — no bump. Force a milestone
  with the release workflow's ``bump`` input (``ver.project_bump_minor`` / ``_major``).

``ver.project_bump_build`` (``X.Y.Z`` -> ``X.Y.Z-001`` -> ``-002``) stays available for manual use
on a feature branch; nothing merged or published ever carries a build suffix.

Usage:
    uv run --no-sync invoke ver.project_bump_patch
    uv run --no-sync invoke ver.project_bump_minor
    uv run --no-sync invoke ver.project_bump_major
    uv run --no-sync invoke ver.project_bump_build
"""

from __future__ import annotations

import re
from pathlib import Path

from ..common.utils import error, success

_VERSION_PATTERN = re.compile(r"^(\d+)\.(\d+)\.(\d+)(?:-(\d+))?$")
_BUILD_WIDTH = 3


def get_repo_root() -> Path:
    """Repo root = the nearest ancestor of the CWD holding both ``pyproject.toml`` and ``VERSION``.

    Deliberately does NOT use ``modules.common.properties.get_repo_root`` — that one searches for
    ``properties.yml``, which is git-ignored (generated by ``inv setup.properties``) and so absent
    in CI, where ``version.yml`` / ``release.yml`` run this.
    """
    for parent in (Path.cwd().resolve(), *Path.cwd().resolve().parents):
        if (parent / "pyproject.toml").is_file() and (parent / "VERSION").is_file():
            return parent
    error("Could not find the repo root (no pyproject.toml + VERSION at or above the CWD)")
    raise SystemExit(1)  # unreachable — error() exits; keeps type checkers happy


def _version_file(repo_root: Path) -> Path:
    return repo_root / "VERSION"


def _read(repo_root: Path) -> tuple[int, int, int, int | None]:
    version_file = _version_file(repo_root)
    if not version_file.is_file():
        error(f"VERSION file not found at {version_file}")
    raw = version_file.read_text(encoding="utf-8").strip()
    match = _VERSION_PATTERN.match(raw)
    if not match:
        error(f"VERSION contents {raw!r} don't match Major.Minor.Patch[-Build]")
    major, minor, patch, build = match.groups()
    return int(major), int(minor), int(patch), int(build) if build else None


def _write(repo_root: Path, version: str) -> str:
    _version_file(repo_root).write_text(f"{version}\n", encoding="utf-8")
    success(f"VERSION set to {version}")
    return version


def bump_patch() -> str:
    """``X.Y.Z[-B]`` -> ``X.Y.(Z+1)``. Every merge to development."""
    repo_root = get_repo_root()
    major, minor, patch, _ = _read(repo_root)
    return _write(repo_root, f"{major}.{minor}.{patch + 1}")


def bump_minor() -> str:
    """``X.Y.Z[-B]`` -> ``X.(Y+1).0``. A milestone release bump (release workflow ``bump=minor``)."""
    repo_root = get_repo_root()
    major, minor, _patch, _ = _read(repo_root)
    return _write(repo_root, f"{major}.{minor + 1}.0")


def bump_major() -> str:
    """``X.Y.Z[-B]`` -> ``(X+1).0.0``. A major release bump (release workflow ``bump=major``)."""
    repo_root = get_repo_root()
    major, _minor, _patch, _ = _read(repo_root)
    return _write(repo_root, f"{major + 1}.0.0")


def bump_build() -> str:
    """``X.Y.Z`` -> ``X.Y.Z-001``; ``X.Y.Z-NNN`` -> ``X.Y.Z-(NNN+1)``. Manual, feature-branch only."""
    repo_root = get_repo_root()
    major, minor, patch, build = _read(repo_root)
    next_build = 1 if build is None else build + 1
    return _write(repo_root, f"{major}.{minor}.{patch}-{next_build:0{_BUILD_WIDTH}d}")


_BUMPS = {"patch": bump_patch, "minor": bump_minor, "major": bump_major, "build": bump_build}


if __name__ == "__main__":
    import sys

    _part = sys.argv[1] if len(sys.argv) > 1 else "patch"
    if _part not in _BUMPS:
        error(f"usage: python -m modules.versioning.project [{'|'.join(_BUMPS)}]  (got {_part!r})")
    _BUMPS[_part]()
